name: eta_school_app
description: APP for ETA School Routes system.

publish_to: "none" # Remove this line if you wish to publish to pub.dev

version: 1.12.16

environment:
  sdk: ">=3.2.0 <4.0.0"
  flutter: ">= 3.19.0 <4.0.0"
dependencies:
  android_intent_plus: ^5.3.0
  background_locator_2: ^2.0.6
  cached_network_image: ^3.2.3
  carousel_slider: ^4.2.1
  connectivity_plus: ^6.1.2
  device_info_plus: ^8.2.2
  dio: ^5.7.0
  firebase_core: ^2.21.0
  firebase_core_platform_interface: ^5.0.0
  firebase_messaging: ^14.9.4
  flutter:
    sdk: flutter
  flutter_local_notifications: ^16.1.0
  flutter_polyline_points: ^2.0.0
  flutter_riverpod: ^2.4.9
  flutter_slidable: ^3.0.1
  flutter_svg: ^2.0.9
  geocoding: ^2.1.1
  geolocator: ^10.1.0
  get: ^4.6.5
  google_fonts: ^6.1.0
  google_maps_flutter: ^2.2.6
  http: ^1.1.2
  image_picker: ^1.0.2
  intl: ^0.19.0
  isar: ^3.1.0+1
  isar_flutter_libs: ^3.1.0+1
  localstorage: ^4.0.1+2
  location: ^5.0.3
  mapbox_maps_flutter: ^2.0.0
  model_viewer_plus: ^1.7.2
  mqtt_client: ^10.3.0
  onesignal_flutter: ^5.0.3
  path_provider: ^2.1.4
  permission_handler: ^11.3.1
  provider: ^6.1.1
  qr_flutter: ^4.1.0
  rflutter_alert: ^2.0.7
  sensors_plus: ^6.1.1
  shared_preferences: ^2.0.17
  table_calendar: ^3.0.9
  url_launcher: ^6.0.0
  visibility_detector: ^0.4.0+2
  wakelock: ^0.6.2
  workmanager: ^0.5.2
  font_awesome_flutter: ^10.8.0

dev_dependencies:
  build_runner: ^2.4.9
  flutter_lints: ^3.0.1
  flutter_test:
    sdk: flutter
  isar_generator: ^3.1.0+1

flutter_icons:
  ios: true

flutter:
  uses-material-design: true

  assets:
    - assets/
    - assets/svg/
    - assets/slides/
    - assets/markers/
