name: MediansSchoolDriver
description: Parent APP for Medians School Routes system.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.2.0 <4.0.0'


dependencies:
  flutter:
    sdk: flutter

  provider: ^6.1.1
  http: ^1.1.2
  shared_preferences: ^2.0.17
  get: ^4.6.5
  flutter_svg : ^2.0.9
  localstorage: ^4.0.1+2
  rflutter_alert: ^2.0.7
  google_maps_flutter: ^2.2.6
  url_launcher: ^6.0.0
  geolocator: ^10.1.0
  flutter_slidable: ^3.0.1
  location: ^5.0.3
  intl: ^0.19.0
  flutter_polyline_points: ^2.0.0
  onesignal_flutter: ^5.0.3
  firebase_core: ^2.21.0
  firebase_core_platform_interface: ^5.0.0
  flutter_local_notifications: ^16.1.0
  carousel_slider: ^4.2.1
  cached_network_image: ^3.2.3
  geocoding: ^2.1.1
  image_picker: ^1.0.2
  google_fonts: ^6.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.1
 

flutter_icons:
  ios: true


flutter:
  uses-material-design: true

  assets:
    - assets/
    - assets/svg/
    - assets/slides/