name: Build Flutter App and Generate Split APKs

on:
  # push:
    # branches: [main]
  pull_request:
      branches: [ "master" ]
  
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: stable
          flutter-version: 3.24.2
      - name: Get dependencies
        run: |
          
          flutter pub get
      - name: Build APKs for specific architectures
        run: flutter build apk --split-per-abi
      - name: Upload arm64 APK
        uses: actions/upload-artifact@v3
        with:
          name: app-arm64.apk
          path: build/app/outputs/flutter-apk/app-arm64-v8a-release.apk
      - name: Upload armeabi-v7a APK
        uses: actions/upload-artifact@v3
        with:
          name: app-armeabi-v7a.apk
          path: build/app/outputs/flutter-apk/app-armeabi-v7a-release.apk
