name: Build Flutter App and Generate Split APKs

on:
  push:
    branches: ['*']
  pull_request:
      branches: [ "master" ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: stable
          flutter-version: 3.19.2
          cache: true

      - name: Get version
        id: get_version
        run: |
          VERSION=$(cat pubspec.yaml | grep 'version:' | cut -d':' -f2 | tr -d ' ')
          echo "::set-output name=version::$VERSION"

      - name: Get dependencies
        run: |

          flutter pub get
      - name: Build APKs for specific architectures
        run: flutter build apk --split-per-abi --tree-shake-icons

      - name: Update apk name'
        id: update_apk_name
        run:  |
          mv -v build/app/outputs/flutter-apk/app-arm64-v8a-release.apk eta-arm64-v8a-${{steps.get_version.outputs.version}}.apk &&
          mv -v build/app/outputs/flutter-apk/app-armeabi-v7a-release.apk eta-armeabi-v7a-${{steps.get_version.outputs.version}}.apk

      - name: Upload arm64 APK
        uses: actions/upload-artifact@v4
        with:
          name: eta-arm64-v8a-${{steps.get_version.outputs.version}}.apk
          path: eta-arm64-v8a-${{steps.get_version.outputs.version}}.apk

      - name: Upload armeabi-v7a APK
        uses: actions/upload-artifact@v4
        with:
          name: eta-armeabi-v7a-${{steps.get_version.outputs.version}}.apk
          path: eta-armeabi-v7a-${{steps.get_version.outputs.version}}.apk
