name: Flutter Tests

on:
  push:
    branches: ['*']
  
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: stable
          flutter-version: 3.24.2
      - name: Get dependencies
        run: flutter pub get
      # - name: 
      #   run: flutter test
